spring.application.name=VinylShop

POSTGRESQL_DATABASENAME = vinylshop2
POSTGRESQL_USERNAME = postgres
POSTGRESQL_PASSWORD = password

# Database url, username en password aanpassen aan jouw configuratie:
# - Vul ze hier "hardcoded" in.
# - Vul de parameters in de run environment in.
# - Maak variabelen zoals:
#       - POSTGRESQL_DATABASENAME = testing
#       - POSTGRESQL_USERNAME = postgres
#       - POSTGRESQL_PASSWORD = geheim
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRESQL_DATABASENAME}
spring.datasource.username=postgres
spring.datasource.password=password

# Jpa instellingen
spring.jpa.show-sql=true

# forces to generate the data structures
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

# database initialization with data.sql after hibernate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

